<!DOCTYPE HTML>
<html>

<head>
<meta charset="utf-8">
<title>后台系统——登录</title>
<link href="<?=STATIC_URL?>/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
body {
	padding-top: 40px;
	padding-bottom: 40px;
	background-color: #f5f5f5;
}

.form-signin {
	max-width: 300px;
	padding: 19px 29px 29px;
	margin: 0 auto 20px;
	background-color: #fff;
	border: 1px solid #e5e5e5;
	-webkit-border-radius: 5px;
	   -moz-border-radius: 5px;
	        border-radius: 5px;
	-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
	   -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
	        box-shadow: 0 1px 2px rgba(0,0,0,.05);
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
	margin-bottom: 10px;
}
.form-signin input[type="text"],
.form-signin input[type="password"] {
	font-size: 16px;
	height: auto;
	margin-bottom: 15px;
	padding: 7px 9px;
}
</style>
</head>

<body>
	<div class="container">
		<form class="form-signin" method="post">
			<h2 class="form-signin-heading">管理员登陆</h2>
			<input type="text" class="input-block-level" placeholder="用户名" name="username" id="username">
			<input type="password" class="input-block-level" placeholder="密码" name="password" id="password">
			<?php if(isset($message)) : ?>
			<div class="alert alert-error">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<?php echo $message;?>
			</div>
			<?php endif;?>
			<button class="btn btn-large btn-primary" type="submit">登陆</button>
		</form>
	</div>
	<script src="<?=STATIC_URL?>/js/jquery.min.js"></script>
	<script src="<?=STATIC_URL?>/js/bootstrap.min.js"></script>
</body>

</html>
