<?php $user = isset($_COOKIE['user']) ? $_COOKIE['user'] : null;?>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<?php if($user) : ?>
			<a class="pull-right btn btn-link" href="/Ucenter/index"><?=$user['user_name']?></a>
			<a class="pull-right btn btn-link" href="/Index/logout">注销</a>
			<?php else : ?>
			<a class="pull-right btn btn-link" href="/Index/login">登陆</a>
			<a class="pull-right btn btn-link" href="/Index/reg">注册</a>
			<?php endif;?>
			<a class="pull-right btn btn-link" href="/">首页</a>
			<div class="nav-collapse collapse">
			<ul class="nav">
			</ul>
			</div>
		</div>
	</div>
</div>
<header></header>