<!DOCTYPE HTML>
<html>

<head>
<meta charset="utf-8">
<title>返利查询</title>
<link href="<?=STATIC_URL?>/css/bootstrap.css" rel="stylesheet">
<link href="<?=STATIC_URL?>/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="<?=STATIC_URL?>/css/index.css" rel="stylesheet"> 
<script src="<?=STATIC_URL?>/js/jquery.min.js"></script>
<script src="<?=STATIC_URL?>/js/bootstrap.min.js"></script>
<script src="http://l.tbcdn.cn/apps/top/x/sdk.js?appkey=21559467"></script>
</head>

<body>
	<?=$this->render('_top.phtml');?>
	<div id="k_main" class="container">
		<?php echo $this->content; ?>
	</div>
	<?=$this->render('_footer.phtml');?>
</body>
</html>