<form class="form-horizontal" action="/User/Index/add" method="post" id="addFrom">
  <div class="control-group">
    <label class="control-label">用户名</label>
    <div class="controls">
      <input type="text" id="user_name" name="user_name">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">密码</label>
    <div class="controls">
      <input type="text" id="password" name="password">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="real_name">真实姓名</label>
    <div class="controls">
      <input type="text" id="real_name" name="real_name">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="alipay">支付宝账户</label>
    <div class="controls">
      <input type="text" id="alipay" name="alipay">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="alipay">联系电话</label>
    <div class="controls">
      <input type="text" id="tel" name="tel">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">状态</label>
    <div class="controls">
      <label class="radio inline">
        <input type="radio" name="status" value="1" checked>
        开启
      </label>
      <label class="radio inline">
        <input type="radio" name="status" value="0">
        关闭
      </label>
    </div>
  </div>
</form>