<?php 
	$userAssoc = Services_User_User::getUserAssoc();
	$statusAssoc = array('0'=>'待返', '1' => '已返');
	$typeAssoc = array('taobao'=>'淘宝', 'paipai' => '拍拍');
?>
<div class="row">
	<?=$this->render('_layout/_sidebar.phtml');?>
	<div class="span9">
		<section>
			<h3>
				我的返利
				<p class="pull-right">已返：<?=$user['has_money']?>元&nbsp;&nbsp;待返：<?=$user['wait_money']?>元</p>
			</h3>
			<form class="form-inline">
				<input type="text" class="input" placeholder="订单号" name="order_num" value="<?=isset($params['order_num']) ? $params['order_num'] : ''?>">
				<select class="input-small" name="status">
					<option value="-1">全部</option>
					<?php foreach($statusAssoc as $k => $v) :?>
					<option value="<?=$k?>" <?php if(isset($params['status']) && $params['status'] == $k):?>selected<?php endif;?>><?=$v?></option>		
					<?php endforeach;?>
				</select>
				<button type="submit" class="btn">搜索</button>
			</form>
			<?php if($fanliList) : ?>
			<table class="table table-hover" id="fanliTable">
				<thead
					<tr>
						<th class="span3"><a href="<?=Gq_Common::buildUrl($base_uri, $params, Gq_Common::toggleOrder($order, 'goods_title'))?>">商品名称<?php if(isset($order['goods_title'])) : ?><i class="icon-chevron-<?=$order['goods_title'] == 'ASC' ? 'up' : 'down'?>"></i><?php endif;?></a></th>
						<th><a href="<?=Gq_Common::buildUrl($base_uri, $params, Gq_Common::toggleOrder($order_num, 'order_num'))?>">订单号(类型)<?php if(isset($order['order_num'])) : ?><i class="icon-chevron-<?=$order['order_num'] == 'ASC' ? 'up' : 'down'?>"></i><?php endif;?></a></th>				
						<th><a href="<?=Gq_Common::buildUrl($base_uri, $params, Gq_Common::toggleOrder($order, 'commission'))?>">返利<?php if(isset($order['commission'])) : ?><i class="icon-chevron-<?=$order['commission'] == 'ASC' ? 'up' : 'down'?>"></i><?php endif;?></a></th>
						<th><a href="<?=Gq_Common::buildUrl($base_uri, $params, Gq_Common::toggleOrder($order, 'pay_time'))?>">支付时间<?php if(isset($order['pay_time'])) : ?><i class="icon-chevron-<?=$order['pay_time'] == 'ASC' ? 'up' : 'down'?>"></i><?php endif;?></a></th>
						<th class="span1"><a href="<?=Gq_Common::buildUrl($base_uri, $params, Gq_Common::toggleOrder($order, 'status'))?>">状态<?php if(isset($order['status'])) : ?><i class="icon-chevron-<?=$order['status'] == 'ASC' ? 'up' : 'down'?>"></i><?php endif;?></a></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($fanliList as $item) : ?>
					<tr id="row_<?=$item['fanli_id']?>">
						<td><?=$item['goods_title']?></td>
						<td><?=$item['order_num']?>(<?=$typeAssoc[$item['type']]?>)</td>
						<td>￥<?=$item['commission']?></td>
						<td><?=$item['pay_time']?></td>
						<td><?=$statusAssoc[$item['status']]?></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
			<?=$this->render('_layout/_pagination_control.phtml');?>
			<?php else:?>
			<div class="well">抱歉，没有找到您所需要的返利信息！</div>
			<?php endif;?>
		</section>
	</div>
</div>