<div class="row">
	<?=$this->render('_layout/_sidebar.phtml');?>
	<div class="span9">
		<section>
			<form class="form-horizontal" id="infoForm">
				<legend>完善信息 —— <?=$user['user_name']?></legend>
				<div class="alert alert-error hide" id="message">
					<button type="button" class="close" data-dismiss="alert">×</button>
					&nbsp;
				</div>
				<div class="control-group">
					<label class="control-label" for="inputAlipay">邮箱</label>
					<div class="controls">
					 	<input type="text" id="inputAlipay" name="email" placeholder="电子邮箱" value="<?=$user['email']?>">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputTel">手机</label>
					<div class="controls">
					 	<input type="text" id="inputTel" name="tel" placeholder="手机号" value="<?=$user['tel']?>">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputRealname">真实姓名</label>
					<div class="controls">
					 	<input type="text" id="inputRealname" name="real_name" placeholder="真实姓名" value="<?=$user['real_name']?>">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputAlipay">支付宝</label>
					<div class="controls">
					 	<input type="text" id="inputAlipay" name="alipay" placeholder="支付宝" value="<?=$user['alipay']?>">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label" for="inputAlipay">QQ</label>
					<div class="controls">
					 	<input type="text" id="inputAlipay" name="qq" placeholder="QQ号码" value="<?=$user['qq']?>">
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<button type="button" class="btn btn-primary" id="subbtn">确认提交</button>
					</div>
				</div>
			</form>
		</section>
	</div>
</div>
<script type="text/javascript">
$('#subbtn').click(function(){
	$('#message span').remove();
	$.ajax({
		url : '/Ucenter/info',
		type : 'post',
		dataType : 'json',
		data : $('#infoForm').serializeArray(),
		success : function(resp){
			if($.type(resp) !== 'object') return;
			if(resp.error == 0){
				window.location.href = location.href;
			}else{
				$("#message").append('<span>' + resp.message + '</span>').show();
			}
		}
	});
});
</script>