<div class="span3">
	<ul class="nav nav-pills nav-stacked affix k_siderbar">
		<?php 
			foreach($this->menu[CURR_MODULE]['sidebar'] as $item) : 
				list($hole, $module, $controller, $action) = explode('/', $item['url']);
		?>
		<li <?php if($controller == CURR_CONTROLLER && $action = CURR_ACTION) : ?>class="active" <?php endif;?>><a href="<?=$item['url']?>"><i class="icon-chevron-right"></i> <?=$item['name']?></a></li>
		<?php endforeach;?>
	</ul>
</div>