<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">	
			<a class="pull-right btn btn-link" href="/Core/Index/logout">登出</a>
			<a class="pull-right btn btn-link" href="/" target="_blank">首页</a>
			<div class="nav-collapse collapse">
			<ul class="nav">
				<?php foreach($this->menu as $module =>$item): ?>
				<li <?php if(CURR_MODULE == $module) : ?>class="active"<?php endif;?>>
					<a href="<?=$item['base']['url']?>"><?=$item['base']['name']?></a>
				</li>
				<?php endforeach;?>
			</ul>
			</div>
		</div>
	</div>
</div>
<header></header>