<style type="text/css">
body {
	background-color: #f5f5f5;
}
</style>
<form class="form-signin" method="post">
	<h2 class="form-signin-heading">朋友，请登录</h2>
	<input type="text" class="input-block-level" placeholder="注册邮箱" name="username" id="username">
	<input type="password" class="input-block-level" placeholder="密码" name="password" id="password">
	<?php if(isset($message)) : ?>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<?php echo $message;?>
	</div>
	<?php endif;?>
	<button class="btn btn-large btn-primary" type="submit">登陆</button>
</form>