<style type="text/css">
body {
	background-color: #f5f5f5;
}
</style>
<form class="form-signin" method="post">
	<h2 class="form-signin-heading">用户注册</h2>
	<input type="text" class="input-block-level" placeholder="用户名（6-12个字符）" name="username" id="username">
	<input type="password" class="input-block-level" placeholder="密码（6-18个字符）" name="password" id="password">
	<input type="password" class="input-block-level" placeholder="确认密码（6-18个字符）" name="password2" id="password2">
	<?php if(isset($message)) : ?>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<?php echo $message;?>
	</div>
	<?php endif;?>
	<button class="btn btn-large btn-primary" type="submit">注册</button>
</form>